### ISSUE TITLE
Feature Request: Ability to pass environment variables

### ISSUE THREAD

**Issue by p-nicolaou** [inf2381/fastlane-plugin-maestro#1]
Hello! Thank you for this awsone plugin.

Would be great if we could pass any variable to flows via Fastfile. For example, we have Android and iOS projects and a single flow that we are "injecting" the `appId`. Via command line that can be achieved using `-e {key}={value}` command.

I can submit a PR for this change. Happy to help :)

**Comment by inf2381** [comment]
Hello! Thanks for using the plugin and sorry for getting back so late on this topic. I hope it is still relevant. What would be the drawback of setting the environment variables before launching the maestro action? 

```ruby
ENV['foo'] = 'bar'
maestro
```

If that's not a viable solution, feel free to create a PR or I'll look into it. 😊

**Comment by p-nicolaou** [comment]
Hello @inf2381. There's nothing wrong against your proposed solution above. I just thought would be nice to cover all Maestro commands, if possible.
In any case, you can review my PR and act accordinlgy

**Comment by inf2381** [comment]
Thanks a lot for your contribution 😊
